version: '3'
services:
  jubilarse:
    container_name: jubilarse
    restart: always
    build: server
    ports:
      - "6000:6000"
    depends_on:
      - jubilarse-postgres
  jubliarse-postgres:
    container_name: jubilarse-postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jubilarse
